### PR TITLE
Changed property observer to use property info instead of property name

### PR DESCRIPTION
**Pull request by omerfarukz**
### Bugs Fixed ###

https://github.com/PrismLibrary/Prism/issues/1676

### PR Checklist ###

- [x ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [x ] Changes adhere to coding standard

### CODE REVIEW

**Comment by brianlagunas** [comment]
This is actually much better. Sometimes it's easy to miss the most obvious approach. Have you confirmed that this works for your scenario?

**Comment by omerfarukz** [comment]
Yes, it work in my scenario. All tests are passed except DirectoryModuleCatalogFixture. Consedired it is not related with this.

**Comment by brianlagunas** [comment]
Cool. Yeah, don't worry about the DirectoryModuleCatalog tests. Those are failing because of the .NET Core 3 target.  We are working on our build server right now, so as soon as we get that fixed, I'll merge.

**Comment by dansiegel** [comment]
Thanks for the PR

**Pull request merged**
