### PR TITLE
fix documentation links

### PR DESCRIPTION
**Pull request by ildoc**
fixed documentation links

### CODE REVIEW

**Comment by krossley** [comment]
I second that!

**Comment by bartlannoeye** [comment]
The current links are working in readthedocs, so why is this change necessary?

**Comment by ildoc** [comment]
oh, i've found those broken links browsing docs here on github, i didn't know about a rtd docs!
there's absolutely no references to it in the whole project ([proof](https://github.com/PrismLibrary/Prism/search?utf8=%E2%9C%93&q=readthedocs))

anyway, it's a small change, so i don't see why not to merge it...

**Comment by krossley** [comment]
Bartlannoeye,
All I know is if you search for prism and go to the Prism Page if you try to look at the docs I get the 404 not found message.  

https://github.com/PrismLibrary/Prism

**Comment by brianlagunas** [comment]
We are in the middle of changing over to read the docs.  As soon as we can verify all the links and docs are working on RTD, then we will be removing the "Documentation" folder and updating all links pointing to the new doc system.

**Pull request merged**
