### PR TITLE
PageDialogService Updates

### PR DESCRIPTION
**Pull request by dansiegel**
﻿## Description of Change

Updates the PageDialogService with additional newer methods that accommodate for the text FlowDirection. Updates the E2E PageDialogService Module to have various pages to explore the Alert, ActionSheet and Prompt API's.

The API's have also been updated to get rid of things in the Xamarin.Forms namespace as we don't want people breaking MVVM with references to UI in their ViewModel. Also addresses bug with TabbedNavigation as this was directly affecting the updated E2E updates.

### Bugs Fixed

- #2316
- #2218, #2295, #2317

### API Changes

List all API changes here (or just put None), example:

Added:

- IKeyboardMapper -> Keyboard Map(KeyboardType)
- KeyboardType enum
- FlowDirection
- Task<bool> IPageDialogService.DisplayAlertAsync(string title, string message, string acceptButton, string cancelButton, FlowDirection flowDirection)
- Task IPageDialogService.DisplayAlertAsync(string title, string message, string cancelButton, FlowDirection flowDirection)
- Task<string> IPageDialogService.DisplayActionSheetAsync(string title, string cancelButton, string destroyButton, FlowDirection flowDirection, params string[] otherButtons)
- Task IPageDialogService.DisplayActionSheetAsync(string title, FlowDirection flowDirection, params IActionSheetButton[] buttons)

Changed:

- Xamarin.Forms.FlowDirection IDeviceService.FlowDirection -> Prism.AppModel.FlowDirection IDeviceService.FlowDirection
- void IDeviceService.SetFlowDirection(Xamarin.Forms.FlowDirection) -> void IDeviceService.SetFlowDirection(Prism.AppModel.FlowDirection)
- Task<string> IPageDialogService.DisplayPromptAsync(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = default, int maxLength = -1, Xamarin.Forms.Keyboard keyboard = default, string initialValue = "") -> Task<string> IPageDialogService.DisplayPromptAsync(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = default, int maxLength = -1, Xamarin.Forms.Keyboard keyboard = default, string initialValue = "")

Removed:

- NavigationMode.Forward (Was only used by Prism.UWP)
- NavigationMode.Refresh (Was only used by Prism.UWP)

### Behavioral Changes

Fixes incorrect behavior experienced in Tabbed Pages where the children were hard coded or explicitly opted into the ViewModelLocator.AutowireViewModel property. This should now 

### PR Checklist

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by tbaggett** [comment]
@dansiegel are there any additional app code changes needed in a Prism.Forms 8 app to restore the navigation behavior seen in a Prism.Forms 7.2 app once the changes in this PR are merged? 

I built the "dialogserviceupdate" branch locally and replaced the Prism.DryIoc.Forms package in my app solution with the local 8.1.33-pre-g4e3ad50e65 copies. I tested the build in the iOS Simulator. 

The navigation behavior changed compared to using Prism.DryIoc.Forms v8.0.0.1909, but still isn't the same as when using 7.2. Navigation to child tab pages are now all happening in the first tab, and the back button is disappearing on the child pages when the navigation animation is completed.

I'm happy to make adjustments to my app code and retest if changes are needed. I can also try to create a test project that reproduces what I'm seeing if that is helpful. Thanks!

**Comment by dansiegel** [comment]
@tbaggett I will need to do some more investigation with the tabbed pages. If you can ping me on the Sponsor Connect Discord we can discuss more so that we can try to get you unblocked.

**Comment by tbaggett** [comment]
Thanks @dansiegel! I tried to sign in to https://sponsorconnect.dev/ using Chrome on my Mac (v88.0.4324.150) after granting Github permissions and clicking the link in the confirmation email. When I click the login link on the site, I see "redirecting to the login screen", then "Loading...", "login successful", and finally "login failed" messaging. I'm not prompted to enter credentials to login.

I also tried it in Safari in case it was a Chrome issue, but it is stuck at the initial "Loading..." screen and a "Cannot load script ...dotnet5.0.2.js" error is in the console. 

Any suggestions on how to access the Discord channel? Thanks again

**Comment by dansiegel** [comment]
@tbaggett if you're having trouble try a hard reload and clear the cache... a little problem I've noticed with Blazor Web Assembly... If that doesn't clear things up for you you can email me dsiegel at avantipoint dot com or dm me on Twitter.

**Pull request merged**
