### PR TITLE
Add nullable annotations to commands

### PR DESCRIPTION
**Pull request by bdovaz**
I have also taken the opportunity to apply the features of new versions of C#.

I have concerns on how to act on the AsyncDelegateCommand when casting. I have chosen to use ! (null-forgiving) but I want your opinion.

### CODE REVIEW

**Comment by bdovaz** [comment]
I understand that what has failed is not my fault since it is in a checkout step.

**Review by dansiegel — APPROVED** [review]

**Comment by bdovaz** [comment]
@dansiegel is the PR ready to merge? You have not answered to the doubt that I have raised initially, I do not know if you agree with my approach or you have not read it.

Thank you!

**Comment by dansiegel** [comment]
@bdovaz just waiting on a review from @brianlagunas

**Review by brianlagunas — APPROVED** [review]

**Comment by bdovaz** [comment]
@brianlagunas my idea is to help you step by step to implement it by parts in different PR, project by project (Example: Prism.Core) and block by block (Example: Commands).

**Comment by dansiegel** [comment]
Thanks for the PR @bdovaz

**Pull request merged**
