### PR TITLE
Fix Navigation Mode when DeepLink from NavigationPage.

### PR DESCRIPTION
**Pull request by nuitsjp**
Please take a moment to fill out the following:

Fixes issue #1046 .

Changes proposed in this pull request:
In the next case, fixed to set true for useModalNavigation.
- Navigation from child page of NavigationPage
- useModalNavigation is null

### CODE REVIEW

**Comment by nuitsjp** [comment]
Completed. Please review.

**Comment by brianlagunas** [comment]
With this fix, you have also uncovered a bug in XF.  When deep linking from within a NavigationPage, the pages are placed on the stack backwards.  Given your code snippet
```
navigationService.NavigationAsync("NavigationPage/ContentPageA");
navigationService.NavigationAsync("ContentPageB/ContentPageC");
```
The result will actually be ContentPageA/ContentPageC/ContentPageB.  Even then ContentPageC will be broken. This used to work in Android, but was broken in UWP.  Now it's broken in both UWP and Android.  I haven't tested iOS yet.

**Comment by brianlagunas** [comment]
Here is the bug: https://bugzilla.xamarin.com/show_bug.cgi?id=56593

**Comment by brianlagunas** [comment]
This was actually fixed with other navigation improvements.

**Pull request closed without merging**
