### PR TITLE
#281 Adding an override to provide custom logic for determing when to restore.

### PR DESCRIPTION
**Pull request by ali-hk**
This pull request addresses #281 Prism.Windows should provide a hook for the application to prevent restoring app state.
Adding an override to PrismApplication to allow the app to provide custom logic that determines whether the app should restore state from a previous session.

### CODE REVIEW

**Comment by bartlannoeye** [comment]
Adding logic to enable skipping restore also opens up for changing the logic that it always tries to restore. This will skip both OnActivateApplicationAsync and OnLaunchApplicationAsync. I don't see this as a real issue, but we should maybe make this clear in the comments of those methods?

Does anyone see above methods being skipped on restore as an issue?

**Comment by ali-hk** [comment]
@bartlannoeye That's a good point, you could theoretically shoot yourself in the foot with this. Probably worth adding that as a comment. It may also be worthwhile to check the SessionStateService to determine if a restore is even possible before calling ShouldRestore.

**Comment by bartlannoeye** [comment]
Please do so.

**Comment by ali-hk** [comment]
@bartlannoeye Added the comment and the SessionStateService check.
Note however that it is *not* possible to skip OnActivateApplicationAsync, because args will not be null in those scenarios and so it will be called. The fact that OnLaunchApplicationAsync is skipped is somewhat obvious once the fact that it's never called during a resume is made clear as well. As such I added a comment to OnLaunched and OnLaunchApplicationAsync.

Here's the lifecycle for reference (before #590):
- Fresh launch:
InitializeShell -> InitializeFrameAsync -> OnLaunchApplicationAsync
- Resume:
InitializeShell -> InitializeFrameAsync
- Alternate activation:
InitializeShell -> InitializeFrameAsync -> OnActivateApplicationAsync

The lifecycle after #590:
- Fresh launch:
InitializeShell -> InitializeFrameAsync -> OnLaunchApplicationAsync
- Resume:
InitializeShell -> InitializeFrameAsync -> OnResumeAppAsync 
- Alternate activation:
InitializeShell -> InitializeFrameAsync -> OnActivateApplicationAsync

It's probably worth adding the lifecycle to a wiki page or something :)

**Comment by brianlagunas** [comment]
@bartlannoeye what's going on with this PR?  It is breaking the build, and I don't see a resolution agreed upon in the thread.  Should we close it?

**Comment by ali-hk** [comment]
@brianlagunas I believe this is only breaking the build because of a merge conflict in the comments that I added/updated on the past two commits.

**Comment by ali-hk** [comment]
@brianlagunas resolved the build failure. Also, based on @bartlannoeye's comments he appeared onboard with this and this PR was just blocked on adding the comments that were requested and checking if restore is even possible. Both of those changes were made.

**Comment by briannoyes** [comment]
I agree with @ali-hk and @bartlannoeye - think this one should be committed with the changes. I'll let one of you do that though since I have been so out of touch with Prism lately. Trying to free up some time to get back in the loop.

**Comment by brianlagunas** [comment]
@ali-hk could you rebase with master so I can merge this in?

**Comment by ali-hk** [comment]
I'm sorry, I'm afraid I don't really have the time to address this at this point in time. If this is blocking anything, please feel free to close the pull request.

**Pull request closed without merging**
