### PR TITLE
Grace for Prism

### PR DESCRIPTION
**Pull request by rinoandrejohnsen**
Please take a moment to fill out the following:

Fixes issue #1273 .

Changes proposed in this pull request:
- This adds Grace as an IOC container for Xamarin, Win10 and Wpf.

### CODE REVIEW

**Comment by rinoandrejohnsen** [comment]
This my first take on this. All tests are good and I have tested the Xamarin - and Wpf implementation on actual apps. Feedbacks are welcome.

**Comment by brianlagunas** [comment]
Your build is broken. You must rebase with master and fix your implementation.

**Comment by rinoandrejohnsen** [comment]
Hate to pull the 'works-on-my-computer' card, but so it does. Have merged in the upstream project and made the changes. Let me know if there is something else that I need to do.

**Comment by brianlagunas** [comment]
Probably a moot point anyways as the chances o this being merged is very slim :)

Plus, similar changes are coming to WPF so you will be updating this again soon anyways.

**Comment by rinoandrejohnsen** [comment]
That's ok for me :)

I will do changes as soon as your pull request is in.

**Comment by brianlagunas** [comment]
PR merged. Don't implement the bootstrapper in WPF. That is going away.  As you can see, it is much easier to implement a new container :)

**Comment by rinoandrejohnsen** [comment]
It, indeed, was much easier to implement. A 'CommonIOCContainer' in a sense - I can dig it. Especially nice for modules since they don't have to depend on a specific container implementation.

With that said, I want to drill a bit on this issue with AppVeyor not building. Can you take a look at it? I have looked trough the logs and from what I can see, there is nothing I can do about from here. If however there is something I can do, please let me know.

**Comment by brianlagunas** [comment]
Sorry, but this isn't something I am going to spend any time on.  As I said before you submitted this PR, this will most likely not even be merged. All I can tell is that you have 3 tests failing.

**Comment by brianlagunas** [comment]
Actually, you should create your own GitHub project for this and then publish it to NuGet.  You don't have to be block by a couple of stubborn project maintainers :)

**Comment by rinoandrejohnsen** [comment]
Fair enough. I could build a case for this, but I understand that you have enough on your plate as it is. Closing this pull request.

**Pull request closed without merging**
