### PR TITLE
Change solution file for AppVeyor

### PR DESCRIPTION
**Pull request by bartlannoeye**
Changed solution files as described in #143.
Also re-enabled failing C#6 code to test build.

Did set up AppVeyor for my branch and after setting environment to "Visual Studio 2015" I got a green build with the code reverted to C#6 (when disabling tests, there was 1 Command test failing).

### CODE REVIEW

**Comment by bartlannoeye** [comment]
The test runs in VS, but fails on AppVeyor, but it's not related to C6# features as far as I can see.

**Comment by bartlannoeye** [comment]
@brianlagunas I'm questioning the correctness of the failing test, which seems to be a near duplicate of another one.
Failing test: line 202: NonGenericDelegateCommandShouldInvokeExplicitExecuteFunc
Passing test: line 394: DelegateCommandFromAsyncHandlerExecuteShouldInvokeExecuteFunc

In the second test you have a DelegateCommand with async handler and actually await the Execute, while in the first it's not awaited.

**Comment by bartlannoeye** [comment]
See #139 for the test.

**Comment by bartlannoeye** [comment]
As an addition, I think the async execute should be called ExecuteAsync instead to make it's async nature clear.

**Comment by brianlagunas** [comment]
I have updated the AppVeyor settings and everything seems to be working as you explained.

**Comment by brianlagunas** [comment]
I think the reason it is named Execute as apposed to ExecuteAsync I so that is can be invoked async from the ICommand interface.  I'm not 100% sure why the Execute was written the way it is, but I am hesitant to mess with it without understanding the thought behind the current approach.

**Comment by briannoyes** [comment]
I was involved with adding the async methods to the command classes but it has been a year and a half since I looked at it.  We can discuss via Skype if you like.

**Pull request merged**
