### PR TITLE
[UWP] PrismApplication - CreateShell and Cleanup

### PR DESCRIPTION
**Pull request by veccie**
Removed old HardwareButton code as this is part of DeviceGestureService now.

The problem with PrismApplication.OnLaunched is that it always assumes that the Window.Current.Content is a Frame. This is not the case when for example implementing the SplitView navigation pattern. When using the SplitView navigation pattern the Window.Current.Content will be a Page with a SplitView and SplitView.Content = rootFrame.

The CreateShell method is similar to the WPF version and adds support for other root elements, for example a Page. In the CreateShell method you are then in full control of the rootFrame and where it should be placed.

I'm not sure what's best though: abstract or virtual. CreateShell has the rootFrame as param which can then be returned as shown in the HelloWorld sample.

Question: In which scenario is OnLaunched called more than once?

### CODE REVIEW

**Comment by briannoyes** [comment]
Thanks @veccie, I think these changes make sense with some minor changes. I would make CreateShell virtual and have it just return the shell passed in. No need to force people to implement CreateShell if they just want to be a single root frame, and your null handling in OnLaunched covers that. I'm not aware of any scenario where OnLaunched would be called more than once, but as the comments indicate, I think if the app is launched from a secondary tile and possibly other launch types besides normal user launch (not sure what all there is in Win10 yet), OnLaunched might not be called, so would need to look into those to make sure the right things are happening on startup.

**Comment by veccie** [comment]
Makes sense, I'll update the PR later today.

**Comment by jorisdebock** [comment]
@veccie great pull request, "createshell" method is very useful when using splitview (you can check it in my example if u want https://github.com/jorisdebock/Prism/tree/master/Samples/Windows10/ExampleApp1)

**Comment by veccie** [comment]
Thanks @jorisdebock that's also one of the main reasons I made it :) I saw your SplitView example but ended up making my own based on Microsoft's sample, which uses a ListView instead of RadioButtons :)

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlNavigation/cs

**Pull request merged**
