### PR TITLE
Upgrade DryIoc from 4.0.4 to 4.0.7

### PR DESCRIPTION
**Pull request by justinhachemeister**
﻿## Description of Change

Upgrade DryIoc from 4.0.4 to 4.0.7

### Bugs Fixed

- N/A

### API Changes

None.

### Behavioral Changes

According to unit tests: none.

### PR Checklist

- [ ] Has tests (if omitted, state reason in description)
  - Tests already exist, ran to verify.
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by justinhachemeister** [comment]
I was not sure whether you would want the pull request to do a version bump or you would handle that after.

**Comment by dansiegel** [comment]
Thanks for the PR. We regularly update the containers as part of our release cycle. This is actually already updated as part of the updates to fix our CI builds.

**Comment by justinhachemeister** [comment]
Thanks for letting me know. Do you communicate your release cycle? I could not find anything but may have missed it.

**Comment by brianlagunas** [comment]
Our release cycle is "when we have time" 😄

**Pull request closed without merging**
