### PR TITLE
Fix call idestructible when using an absolute uri

### PR DESCRIPTION
**Pull request by nuitsjp**
Fixes issue #862 .

Changes proposed in this pull request:
- Call IDestructible when using an absolute URI
Please see NavigationService around line 178.
- Added some test cases for IDestructible
But DeepLink tests are not working right now
For details, please see the following
https://github.com/PrismLibrary/Prism/issues/862#issuecomment-278538523

### CODE REVIEW

**Comment by nuitsjp** [comment]
Remaining tasks:
- Fixed a problem that the test did not work correctly with multi-thread

**Comment by nuitsjp** [comment]
All done.
Please review.

**Comment by nuitsjp** [comment]
All done.
Please review.

**Comment by brianlagunas** [comment]
instead of making the PageNavigationEventRecoder behavior static, why not make it instance based so that you don't have to worry about running tests in parallel?

**Comment by brianlagunas** [comment]
Actually, why is the PageNavigationEventRecorder needed?  Can you just check if the DestroyCalled property has been set?

**Comment by nuitsjp** [comment]
**Why Pagenavigationever is a static-based implementation:**
How do I access the Recorder instantiated with Fixture from View or ViewModel?
I had no good idea.
Do you have any good ideas?
If you can parallel tests, that would be the best.

**Why is the PageNavigationEventRecorder needed?:**
I think that events are important to be issued in the correct order.
Actually, the first plan did not behave correctly.
https://github.com/PrismLibrary/Prism/issues/862#issuecomment-278891941

And actually, I have other concerns.
```cs
NavigationService.NavigateAsync("MyNavigationPage/PageA/PageB/PageC");
```

At this time, Events are issued like this.
```txt
PageCViewModel#OnNavigatingTo
PageBViewModel#OnNavigatedFrom
PageCViewModel#OnNavigatedTo
PageBViewModel#OnNavigatingTo
PageAViewModel#OnNavigatedFrom
PageBViewModel#OnNavigatedTo
PageAViewModel#OnNavigatingTo
MyNavigationPageViewModel#OnNavigatedFrom
PageAViewModel#OnNavigatedTo
MyNavigationPageViewModel#OnNavigatingTo
MyNavigationPageViewModel#OnNavigatedTo
```
Is this working correctly?
I think that you should test the order of events issue.

**Comment by nuitsjp** [comment]
I thought overnight. . .
I propose to divide Issue into two (or three).

1. Give up on testing the event order with this Issue  
Close with absolute path IDestructible implementation only
2. Add a new Issue to properly test the event issue order  
3. And if the event order of DeepLink is not appropriate, add that Issue  

It is not easy to balance event order and multithread test.  
And I want to test the order of events.  
However, I think that it is better to separate the problem from this PR.
If so, delete PageNavigationEventRecoder once.

What do you think of this proposal?

**Comment by nuitsjp** [comment]
Successfully enabled parallel execution of PageNavigationEventRecorder.
I responded by setting an instance of PageNavigationEventRecorder to PageNavigationServiceMock.
Therefore, please give me two advice.

1. Can I leave the function to evaluate the order of Events?  
1. Is the above Case B behavior appropriate?
If inappropriate, should I Fix on this Issue? Or may I add another Issue?

**Comment by brianlagunas** [comment]
This is great!  Yes you can leave the order of the events.  When deep linking, the pages are built in reverse order.  So the order of the events is correct for deep links is correct.

**Pull request merged**
