### PR TITLE
Adds Support for Generics to ActionSheetButton

### PR DESCRIPTION
**Pull request by dansiegel**
For #836

### CODE REVIEW

**Comment by brianlagunas** [comment]
Way too many features going on in this PR, without even deciding which ones will be adding :)

**Comment by dansiegel** [comment]
Easy enough to strip something out... but the included features would make it a lot easier to use.

**Comment by brianlagunas** [comment]
I don't like giving too many ways of doing something and inflating an API surface.  I will review when I have a chance.

**Comment by powerdude** [comment]
Can we also get unit tests and examples for this?  It seems like a good thing to have but I'm sure an example would help

**Comment by dansiegel** [comment]
Replaced by #984

**Pull request closed without merging**
