### PR TITLE
NetStandard Support & CI Integration

### PR DESCRIPTION
**Pull request by dansiegel**
- [x] updates expired UWP Sandbox cert
- [x] updates nearly expired UWP XF Sandbox cert
- [x] Automates build and release process #412
  - [x] Build projects in Release configuration
  - [x] Run all tests (Windows Tests cannot be run on Windows Server)
  - [x] Zip up assemblies for manually referenced projects
  - [x] Package NuGets
  - [x] Build Release-Sign configuration for signed containers and Release configuration for unsigned containers (StructureMap)
- [x] Builds both Sandbox projects in Debug
- [x] Builds Prism_XF with the Test configuration to run tests, and again in Release for packing
- [x] Build Core, Windows, Wpf, & XF separately so we can more easily spot where any failing tests are
- [x] Updates the Prism Core and all XF projects to netstandard1.0 or as necessary for the DI container #683
- [x] NetStandard packages are macOS ready #1027

## Note:

UWP Developers may need to add the following file in the same directory as their solution file:
**Directory.Build.props**
```
<Project>
  <!-- Workaround for https://github.com/dotnet/sdk/pull/908 -->
  <Target Name="GetPackagingOutputs" />
</Project>
```

### CODE REVIEW

**Comment by weitzhandler** [comment]
What netstandard version is it targeting?

**Comment by dansiegel** [comment]
@weitzhandler We're targeting netstandard1.0 the same as Xamarin Forms. This also gives us backwards compatibility for those who aren't ready to update their projects from PCL to netstandard. 

**Note:**
- Autofac targets netstandard1.1, as a result Prism.Autofac.Forms targets netstandard1.1 not 1.0
- Ninject was migrated from `Portable.Ninject` to the official Ninject package. 
- Ninject targets netstandard1.3 and netstandard1.5, so Prism.Ninject.Forms has to match the container rather than target 1.0.

**Comment by weitzhandler** [comment]
That's great.
What's gonna be the recommended DI container? Looks like Unity is not maintained, does it even support netstandard?

**Comment by dansiegel** [comment]
@weitzhandler Unity is not being maintained as far as I know either, and the existing package does not directly support NetStandard. NetStandard though is promise based which gives us a lot more flexibility than with PCL. If you take a look at the changes to [Prism.Unity.Forms.csproj](https://github.com/PrismLibrary/Prism/pull/1057/files#diff-d8dae957ee4d7df315e740c6c293eb36) you'll notice a `PackageTargetFallback`. We're able to use that with NetStandard to say "hey I know this package isn't theoretically compatible with my library, but I swear it really will be ok on the platform I implement it on". This is why when the question has come up about how to use the 6.3.0 release with NetStandard I keep pointing people to the preview templates.

As for the Official DI Container... 
> Pick your container of choice.
> There is no "official" container.
> My samples use Unity, because that's what I like to use.
> -@brianlagunas 

That said, if you look at the samples I've done, you'll notice they're using DryIoc because that's the container I like.

**Comment by weitzhandler** [comment]
ohwow what does that mean? Can we start celebrating netstandard?

**Comment by dansiegel** [comment]
there are some updates I need to make to the CI scripts and then you'll start seeing updates pushed to MyGet as features get merged.  But NetStandard is here!!!

**Pull request merged**
