### PR TITLE
[WIP]Fix navigation service and unit test

### PR DESCRIPTION
**Pull request by nuitsjp**
Please take a moment to fill out the following:

Fixes issue #1044 #1045 #1046  .

Changes proposed in this pull request:
- #1044 When Detail of MasterDetailPage is null, the value is set to Detail.
https://github.com/PrismLibrary/Prism/commit/892c6cc6f72c89067004aaf2b5f68fb0d8dc3b86

- #1045 When calling NavigateAsync with NavigationPage, old page's Destroy on the stack is not called
https://github.com/PrismLibrary/Prism/commit/70c5ecd002b2efbd58cf4922ae8cbd1053b8702d

- #1046 When calling DeepLink from Navigation Stack, the second page becomes Modal navigation
not started yet. I will do it.

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thank you for the great PR.  I would like to request that each issue being fixed is placed in a separate PR.  This way I can concentrate on confirming one issue at a time.  One PR per issue :)

Would this be a problem?

**Comment by nuitsjp** [comment]
No problem.
I've been repairing while understanding so far. Therefore, I did refactoring Unit Test at the same time.
But now I think I could fully understand it. Split the RP.
Please give me some time.

**Comment by brianlagunas** [comment]
ありがとうございます！

**Comment by nuitsjp** [comment]
Split and PR again.

**Pull request closed without merging**
