### PR TITLE
Fix absolute navigation of UWP

### PR DESCRIPTION
**Pull request by nuitsjp**
Fixes issue #932 .

Changes proposed in this pull request:
- Add Parse method to UriParsingHelper.
- Update NavigateAsync on PageNavigationService.
- Add unit test for absolute navigations.

### CODE REVIEW

**Comment by brianlagunas** [comment]
While this new Parse method fixes the uri's that start with a "/", it breaks a valid absolute URI

```
        [Fact]
        public void ParseUriThatStartsWithHttp()
        {
            var uri = UriParsingHelper.Parse(_absoluteUri);
            Assert.NotNull(uri);
            Assert.True(uri.IsAbsoluteUri);
        }
```

**Comment by brianlagunas** [comment]
Also, custom protocols are broken:
```
        [Fact]
        public void ParseUriThatStartsWithCustomProtocol()
        {
            var uri = UriParsingHelper.Parse("myApp:///MainPage");
            Assert.NotNull(uri);
            Assert.True(uri.IsAbsoluteUri);
        }
```

**Comment by nuitsjp** [comment]
Add unit tests.

- For _absoluteUri
- For absolute uri with out protocol ("/MainPage?id=3&name=brian")
- For _deepLinkAbsoluteUri ( when custom protocol )
- For _deepLinkRelativeUri

Fix Bugs.

- When custom protocol

Please, ReReview!

**Comment by brianlagunas** [comment]
ありがとうございました

**Pull request merged**
