### PR TITLE
Prism.munq

### PR DESCRIPTION
**Pull request by magicmonty**
Added support for the Munq DI container (see https://munq.codeplex.com).

This is WIP, because the Nuget Package for Munq is currently not strong named, therefore the Tests will currently fail.

What is the opinion here? Do I have to sign this strongly?

### CODE REVIEW

**Comment by brianlagunas** [comment]
I wish you would have submitted an issue to discuss adding this before you took the time to work on a PR.  Unfortunately, this is not a container we will be adding support for at this time.

**Comment by magicmonty** [comment]
No problem, I need this anyway. So I make my own NuGet package repo. I just thought, this could be a good fit here.

**Comment by brianlagunas** [comment]
I understand.  This is just not a popular enough container for us to take responsibility of and support.  For sure you can create your own Nuget and put it up there so all who need it can benefit.

**Comment by djcparker** [comment]
@brianlagunas  maybe it is worth adding a "community" packages section to the docs?

**Comment by brianlagunas** [comment]
@djcparker Great idea!

**Pull request closed without merging**
