### PR TITLE
Regions in templates

### PR DESCRIPTION
**Pull request by dvorn**
PR for #694 
## Changes
- In a search for RegionManager in a visual tree, include TemplatedParent of a control.
- Recursion in FindRegionManager method replaced by a loop (optimization).

### CODE REVIEW

**Comment by brianlagunas** [comment]
Please also provide unit tests

**Comment by dvorn** [comment]
@brianlagunas There are obvious difficulties in doing this, because the algorithm consists of traversing the visual tree.  The change is in handling not only the Parent node but also the TemplatedParent.  

Note that currently the tests for RegionManagerRegistrationBehavior do not include any traversing of visual tree.

**Comment by dvorn** [comment]
@brianlagunas Test added.

**Comment by brianlagunas** [comment]
I have decided not to support this out of the box in the framework.

**Pull request closed without merging**
