### PR TITLE
Features/1087 simple injector

### PR DESCRIPTION
**Pull request by WonkiDonk**
Fixes issue #1087.

Added support for `Prism.SimpleInjector.Forms`. Tested on a sample app.

### CODE REVIEW

**Comment by WonkiDonk** [comment]
Included some changes from a review by @dansiegel in Slack.

**Comment by WonkiDonk** [comment]
I had trouble running the tests, actually. Some of the tests seem to rely upon a `TESTS` compiler directive being defined, but I can't find that anywhere. I've added it to the `Prism.SimpleInjector.Forms` project to get the tests running.

**Comment by WonkiDonk** [comment]
Hey @dansiegel. Thanks for your patience. I _think_ I've fixed the build issues now. When I originally added the `Prism.SimpleInjector.Forms` and associated test projects, Visual Studio played around with the configurations, which broke the `Test` build configurations (hence why I thought there'd need to be a compiler directive defined for this). I rolled back the changes to the solutions files and re-applied (paying careful attention to the changes that were made by VS).

I've tested all solutions locally and they all work fine. Hopefully this facilitates closing the PR!!

**Comment by brianlagunas** [comment]
Hey @dansiegel what do you think about this PR?

**Comment by dansiegel** [comment]
@WonkiDonk you'll need to resolve some merge conflicts when you get a moment.

**Comment by rdrrichards** [comment]
@brianlagunas Have you eased up on the idea that you were no longer going to allow a container to only support one Prism platform? If so, I am still thinking about starting a Simple Injector implementation for Prism WPF.

**Comment by brianlagunas** [comment]
@rdrrichards Honestly, the only platforms I care about is WPF and XF. Looks like we can get both of those now :).  Go for it.

**Comment by brianlagunas** [comment]
@rdrrichards I would like to mention that you will loose a lot of the features of dynamic module loading when using Simplenjector.

**Comment by rdrrichards** [comment]
@brianlagunas I will keep that in mind, thanks. If I think that it will become, or cause issues, I will give you a heads up. Last thing I want to do is have this become a burden for the team. I just think it will be fun, and a good way for me to contribute. Thanks again.

**Comment by dansiegel** [comment]
@WonkiDonk just a heads up when PR #1113 gets merged it'll simplify what you need in the csproj

**Comment by WonkiDonk** [comment]
I've resolved the merge conflict and ensured `Prism.SimpleInjector.Forms` has been added to `PrismLibrary.sln`. Should be good to go, @dansiegel 👍

**Comment by dansiegel** [comment]
So one issue right off the bat is that you cannot register the Xamarin Forms NavigationPage. Doing so throws an exception since it has more than one constructor.

**Comment by WonkiDonk** [comment]
Oh. I'll take a look over the weekend.

**Comment by brianlagunas** [comment]
Where are we on this PR?  I would like to move it forward, or close it.  Thanks.

**Comment by brianlagunas** [comment]
Since there hasn't been any movement on this PR I'm going to close it.  When you find some free time to finish it, simply resubmit it.  Thanks for the initial attempt.

**Pull request closed without merging**
