### PR TITLE
NuGet dependencies should follow project references

### PR DESCRIPTION
**Pull request by bartlannoeye**
Following on #1062

### CODE REVIEW

**Comment by dansiegel** [comment]
This is not needed as it is being redone

**Comment by bartlannoeye** [comment]
Looks like I overlooked your work on .net standard #mailboxoverload

**Comment by dansiegel** [comment]
@bartlannoeye we're going to be splitting UWP and WPF into separate packages so each platform can get updates independent of one another, and I'll be updating the UWP projects to the new MSBuildSDK format. Also the nuspecs are getting moved into a centralized build folder that will have all of the build scripts so you can build locally or on AppVeyor.

**Comment by brianlagunas** [comment]
because we are splitting out the UWP nuspecs I am closing this PR.  We should have a lot more flexibility regarding releasing platform updates with everything having it's own packages.

**Pull request closed without merging**
