### PR TITLE
Change Register Command to Return this

### PR DESCRIPTION
**Pull request by Shayon**
https://github.com/PrismLibrary/Prism/issues/377

### CODE REVIEW

**Comment by brianlagunas** [comment]
Would having this same fluent API be helpful on UnregisterCommand too?

**Comment by Shayon** [comment]
Good point @brianlagunas, I went ahead and did that.

**Comment by brianlagunas** [comment]
Actually the more i think about it, the more I can't see the need for this fluent API.  In what scenario are you registering multiple commands in a VM with a single CompositeCommand?

**Comment by Shayon** [comment]
@brianlagunas Hmm, am I perhaps misusing `CompositeCommand`?  In my case I have a button that binds to a composite command in my ViewModel.  In the constructor for my VM I initialize the composite command and register several delegate commands, let's say only 2 in this case.  One command would be something like doing the action that I want the button to do, and the other command is part of my analytics, telling me that that button got clicked.

**Comment by brianlagunas** [comment]
That is not the intention of a CompositeCommand.  There are many ways to integrate analytics into your apps, but I would not be using a CompositeCommand to do it.

**Comment by Shayon** [comment]
@brianlagunas Hmm, let's say I have 3 buttons, and each have a delegate command in the VM, then I have a fourth button that is "Push All Buttons", to me it seems that this would be the appropriate place to use a composite command.  Could you suggest something as an alternative @brianlagunas?

**Comment by brianlagunas** [comment]
No, I wouldn't use it for that either.  I would just have a 4th command that called the logic of the other 3 commands.  If everything happens in the same VM, there is no need for a CompositeCommand.  CompositeCommands are meant to support cross-view and cross-module communication.

**Comment by Shayon** [comment]
I see now. Thanks for the explanation.

**Pull request closed without merging**
