### PR TITLE
Fix destory older pages when navigation from NavigationPage

### PR DESCRIPTION
**Pull request by nuitsjp**
Please take a moment to fill out the following:

Fixes issue #1045.

Changes proposed in this pull request:

When there are multiple pages in Navigation Stack, when navigation from NavigationPage, Destroy of removed page from Stack is not called.
Fixed this problem.

### CODE REVIEW

**Comment by nuitsjp** [comment]
Completed. Please review.

**Comment by brianlagunas** [comment]
Can you please rebase so I can start reviewing this PR :)

**Comment by nuitsjp** [comment]
OK, I will respond during a few days.
Probably it will be about 28 days.
I want to fix UnitTest a little.

**Comment by nuitsjp** [comment]
I tried Rebase, but I'm not sure if this is fine.
If there seems to be a problem, I would like you to tell me that it will be rebuilt.

I have another consultation.

I fixed UnitTest for ViewModelLocatorFixture#ShouldUseCustomDefaultViewTypeToViewModelTypeResolverWhenSet.
After executing this UnitTest, all ViewModel becomes ViewModelLocatorFixture.
For this reason, other tests result in errors.
But maybe not a very good test code.
Could you tell me if there is a better idea?

**Comment by brianlagunas** [comment]
I don't think the re-base was done properly.  It seems you pulled in all the changes instead of rebasing.  Could you please rebase?  Maybe it will be easier for you to close this PR and open a new one?

I am not sure I understand the issue with the test.  Can you open a new issue so we can discuss the issue and discuss possible fixes?

Thanks for your great work!

**Comment by nuitsjp** [comment]
OK. I make it again.
And the test code creates another Issue.

**Comment by nuitsjp** [comment]
I made a new PR #1051 , so I will close it.

**Comment by nuitsjp** [comment]
I was wrong.
Here is the correct PR.

**Comment by nuitsjp** [comment]
I made a new PR #1051 , so I will close it.

**Pull request closed without merging**
