### PR TITLE
Need Access to the DefaultViewTypeToViewModelTypeResolver, to determi…

### PR DESCRIPTION
**Pull request by vsmike**
I need Access to access DefaultViewTypeToViewModelTypeResolver, to call the method  using IModule as a base class for viewModels, this works create, as separate based class with an attribute to determine which view should have access to which region

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks for the PR.  I will review this after vacation.  I return from vacation the week on the 24th.

**Comment by briannoyes** [comment]
Hi @vsmike, this pull request looks pretty harmless, but would like to understand your scenario a little better before pulling it in because I don't understand the tie with modules and view model base classes you mention. Your PR code would make it so you can get back the Func<Type,Type> that is the view model type resolver, but curious how you are going to use that. Do you invoke it yourself to see what Type of VM a given view might produce and then execute some other logic based on that?

**Comment by vsmike** [comment]
Yes, that is the intent Type of VM a given view might produce, for callback discovery.  I was also able to do this operation by Implementing a custom ModuleInitializer as well, so this request at this point could be ignored.

Best regards,

Michael Arnwine
Solution Architect
[cid:image001.jpg@01CC30FF.DAF62560]


Office: 281.282.0865
Direct: 210-737-4712
E-mail: michael.arnwine@flowcal.com<mailto:michael.arnwine@flowcal.com>

[cid:image002.png@01D0CA06.1487C100]<https://www.facebook.com/flowcalsoftware>[cid:image003.png@01D0CA06.1487C100]<https://www.linkedin.com/company/flow-cal?trk=company_logo>[cid:image004.png@01D0CA06.1487C100]<https://twitter.com/flow_cal>[cid:image005.png@01D0CA06.1487C100]<https://www.youtube.com/user/FLOWCAL1>

CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and privileged information, and unauthorized disclosure or use is prohibited. If you received this email in error, please notify the sender and delete this email from your system. Thank you.

**Comment by briannoyes** [comment]
OK, going to close this out then. Thanks.

**Pull request closed without merging**
