### PR TITLE
DryIoc container support for WPF

### PR DESCRIPTION
**Pull request by AlesDo**
I have implemented the DryIoc support for WPF as we discussed in issue #811.
Please review if you are ok with the implementation. 
The main issue I had is DryIoc assemblies are not signed by default so I added a power shell script that automatically signs them when building if they are not signed yet. The script is added also to the final NuGet package where I use a MsBuild target to do the same thing.

### CODE REVIEW

**Comment by brianlagunas** [comment]
We do not take on the responsibility of signing dependent assemblies.  Please remove any scripts or actions related to signing DryIoC.  This is the responsibility of the author.

**Comment by AlesDo** [comment]
The author does not provide a signed version he just includes the key and a script to sign them if you need it. I just adapted the script to do it automatically. I saw all assemblies are signed so I wanted to make it the same.
I will then remove the signing and also the Prism.DryIoc.Wpf assembly will be unsigned.

**Comment by brianlagunas** [comment]
Just to clarify, do not modify any of the existing Prism assemblies. Only the new DryIoc feature related assemblies.

**Comment by AlesDo** [comment]
Yes this is what I meant I will change only the one I added.

**Comment by AlesDo** [comment]
I have added a fix for the RegisterForNavigation extension method and a unit test. While using the code I found that an error happened when the RegionNavigationContentLoader tried to resolve the view.

**Comment by brianlagunas** [comment]
Make sure that DryIoC can automatically resolve concrete classes.  Just ran into this in Xamarin.Forms.

**Comment by AlesDo** [comment]
Ok will look at this have to see what is the case is in XF. DryIoc can resolve concrete classes. I think it is just a matter of proper setup it is more strict in some cases. For the issue I had with the navigation I just had to register differently for it to work.

**Comment by AlesDo** [comment]
I checked again and for me an application similar to the XF sample with navigation and automatic ViewModel resolution works ok. I have added the automatic concrete type resolution on the container. I also added a comment in the XF issue #889 so you know what to enable there for it to work.

**Comment by brianlagunas** [comment]
Thanks for taking the time to create this PR.  Your community is grateful.

**Pull request merged**
