### PR TITLE
Ninject template for Xamarin Forms

### PR DESCRIPTION
**Pull request by dansiegel**
Adds Visual Studio template for Prism Applications using Xamarin Forms and Ninject.

### CODE REVIEW

**Comment by brianlagunas** [comment]
Actually before we do this, we have to create a new NuGet package called Prism.Ninject.Forms.  This I sbecause of the issue of supporting UWP in two different ways (native UWP, and XF UWP).  So our containers need their own Forms package.  Can you create the Prism.Ninject.Forms nuspec in a separate PR, then update the package references in this PR? :)

**Comment by dansiegel** [comment]
Yeah not a problem. I can get that up in a little bit.

**Comment by brianlagunas** [comment]
did you just want to update the logos as we discussed on this before I merge, or would it be easier of me to merge and then update them?

**Comment by dansiegel** [comment]
if you can merge this, I'll make the updates for the SplashActivity for all of the templates in one PR, and the logo's in another as we discussed.

**Pull request merged**
