### PR TITLE
Use EscapedCodeBase to correctly handle special characters

### PR DESCRIPTION
**Pull request by dvorn**
Fixes issue #926 per https://connect.microsoft.com/VisualStudio/feedback/details/750678/codebase-does-not-correctly-escape-character

Changes proposed in this pull request:
- Use Assembly.EscapedCodeBase instead of Assembly.CodeBase

### CODE REVIEW

**Comment by brianlagunas** [comment]
Please provide tests

**Comment by dvorn** [comment]
@brianlagunas Added a test.  But please do not merge right now.  There seemingly is a problem with determining the module file size in FileModuleTypeLoader related to the same Uri.  I will look into that.

**Comment by dvorn** [comment]
Now it's OK

**Comment by brianlagunas** [comment]
Great work!

**Pull request merged**
