### PR TITLE
GetWindow(this) can return null

### PR DESCRIPTION
**Pull request by pdinnissen**
In my tests GetWindow(AssociatedObject) was more reliable than GetWindow(this), but I was not sure I could not prove it definitely.  So I compromised and suggested a coalesce.

### CODE REVIEW

**Comment by brianlagunas** [comment]
In your test did GetWindow(AssociatedObject) ever come back null when GetWindow(this) did not, and vice-versa?

**Comment by pdinnissen** [comment]
In my limited testing GetWindow(this) always returns null, while GetWindow(AssociatedObject) always returns my ShellWindow.  Because I hadn't tested thoroughly (my current application and another sample app), I didn't feel it would be appropriate to dismiss GetWindow(this).  I just wanted to contribute that GetWindow(AssociatedObejct) allowed me to set the Owner field.

**Comment by brianlagunas** [comment]
Can you provide a repo?  It may very well be that we should be using GetWindow(AssociatedObject) and drop GetWindow(this) all together.

**Comment by brianlagunas** [comment]
So I did a little playing around, and I think you are right.  We should be using GetWindow(AssociatedObject).  Can you modify your PR to remove the use of GetWindow(this)?

**Comment by pdinnissen** [comment]
Modified.  Next contribution, I'll make sure to include a sample repo.

**Comment by brianlagunas** [comment]
Thanks for the PR, and good catch!

**Pull request merged**
