### PR TITLE
DelegateCommand.RaiseCanExecuteChanged on UI Thread

### PR DESCRIPTION
**Pull request by brianlagunas**
now DelegateCommand uses the SynchronizationContext to post the CanExecuteChange event to the proper thread.  Fixes issues #299, #322, and #608

### CODE REVIEW

**Comment by powerdude** [comment]
Hey, looks good.  I dont know if i missed it, but I'd suggest testing an async Task method too in addition to async void since that's really not the recommended pattern, but it is required to do sometimes.

**Comment by dvorn** [comment]
@brianlagunas  I maybe misunderstand something, but wouldn't it be better from perf point of view to have

`if (_synchronizationContext != null && _synchronizationContext != SynchronizationContext.Current)`

so that if we're on the same context invoke the event directly?

On the other hand, current implementation is closer in behavior to what we had earlier with WeakEventHandlerManager.

**Comment by dvorn** [comment]
@brianlagunas This implementation differs from what we had with WeakEventHandlerManager in the following:

In WeakEventHandlerManager the SynchronizationContext was captured in the static constructor of the class so it was associated with the main (GUI) thread.

In this implementation the SynchronizationContext is captured in the constructor of DelegateCommand which will usually be called in the constructor of View Model.  Hence, View Models should be created on the GUI thread.

This is OK for ViewModelLocator, but probably this may be a problem for certain View Model-first scenarios.

**Comment by brianlagunas** [comment]
Good catch!  I'll update the code to reflect your recommended changes.

**Comment by brianlagunas** [comment]
Of course all the tests break once I do that :)

**Comment by brianlagunas** [comment]
So when I add this line
```
if (_synchronizationContext != null && _synchronizationContext != SynchronizationContext.Current)
                _synchronizationContext.Post((o) => CanExecuteChanged?.Invoke(this, EventArgs.Empty), null);
```
The tests fail because the test runner always uses a different sync context for each test, and due to the async nature, the test method finished before the Post has completed.  FAIL!  I am not sure how to fix this to where the tests pass.  If you have any insights on how this, I would appreciate the help.  Other wiss I'll just leave it at 
```
if (_synchronizationContext != null)
                _synchronizationContext.Post((o) => CanExecuteChanged?.Invoke(this, EventArgs.Empty), null);
```
so everything will work.

**Comment by brianlagunas** [comment]
Actually, after investing this some more, the culprit is making the sync context static
```
private static readonly SynchronizationContext _synchronizationContext = SynchronizationContext.Current;
```
This is the root of the issue.

**Comment by dvorn** [comment]
@brianlagunas Does it work if you omit comparing of the contexts?  Note that with WeakEventHandlerManager it worked. If not, then we need to make this static field be initialized exactly at the time WeakEventHandlerManager was initialized.

**Comment by brianlagunas** [comment]
@dvorn It is not an issue with the comparing of contexts, it's an issue with the sync context being static and testing it reliably with xUnit.  t functions just fine, it's just getting the tests to pass which is proving to be difficult.

**Comment by brianlagunas** [comment]
I can't get xUnit tests to pass for the life of me.  It's quite frustrating.  It has to do with each test getting a different sync context, and I don't have the original to monitor for completion of the post process before checking the asserts.  I have no idea how the previous tests pasts, because they would have the same issue.

**Comment by brianlagunas** [comment]
Before the tests were using MSTest, I bet that a sync context was never created in those tests, which is why they would pass.  xUnit actually creates a sync context for each test, but I have no way of waiting for the Post to complete before checking the asserts, which run and fail before it's ready.

**Comment by dvorn** [comment]
@brianlagunas  I do not see your current code but note what @powerdude said above: the test methods should return Task instead of void for test system to be able to wait for the test to complete.

**Comment by brianlagunas** [comment]
using Task doesn't matter.  The issue is that the new static variable to hold the sync context is set to a different sync context of the tests.  I cannot Assert a value until after the sync context post has occurred.

For example:
```
        [Fact]
        public void RaiseCanExecuteChangedRaisesCanExecuteChanged()
        {
            var handlers = new DelegateHandlers();
            var command = new DelegateCommand<object>(handlers.Execute);
            bool canExecuteChangedRaised = false;
            command.CanExecuteChanged += delegate { canExecuteChangedRaised = true; };

            command.RaiseCanExecuteChanged();

            //post hasn't completed so this fails
            Assert.True(canExecuteChangedRaised);
        }
```

**Comment by dvorn** [comment]
Ah, I see.

**Comment by brianlagunas** [comment]
Actually just found out that in UWP, if you have multiple top-level windows, each has their own UI thread....so using a static would capture the wrong context.  This means we can't use the static approach after all.

**Comment by pculver** [comment]
Any possibility of a release for this?  I was trying to upgrade a large project from Prism 5 to 6 and this issue is preventing the upgrade.   There would be to many places to change this....

**Comment by brianlagunas** [comment]
@pculver See this thread issue #648 

You'll just have to wait a couple more weeks.

**Comment by pculver** [comment]
Great!  Thanks for the update.

**Pull request merged**
