### PR TITLE
refactoring build props

### PR DESCRIPTION
**Pull request by dansiegel**
Refractors build props to centralize a lot of duplicated fields across SDK style projects including NuGet properties, Test dependencies and provides a way to determine if the project is 

- the Core project
- a UWP project
- a WPF project
- a Forms project
- a Test project

### CODE REVIEW

**Comment by brianlagunas** [comment]
looks like there are conflicts now.. Sorry about that :)

**Comment by dansiegel** [comment]
figured we would... no problem

**Comment by brianlagunas** [comment]
This thing is still broken. Wassup with that  :)

**Comment by dansiegel** [comment]
Replaced by PR #1182

**Pull request closed without merging**
