### PR TITLE
Automate build and release process #412

### PR DESCRIPTION
**Pull request by joacar**
First attempt to automate build and release process.
- [x] Handle different configuration's such as `release` and `release-signed` for projects
- [x] How to resolve properties for different .nuspec's when packing. E.g Prism.Forms requires coreVersion and Prism.Unity.Forms requires formsVersion
  *\* Read all values from hardcoded assemblies
- [x] How to resolve nuget version
  *\* Use convention by replacing .nuspec with .dll and search in bin folder. Prism.Core.nuspec needs special care since the assembly is Prism.dll
- [x] Testing custom xamarin.forms applications require build configuration/compilation symbol (see #517 discussion)
- [ ] Automate creating of git hub release (?)
- [ ] Zip binaries/nupkgs/everything
  Comments appreciated :)
# 412

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks!  I'll check this out next month.  I am slammed with work and then I have Evolve next week.

**Comment by joacar** [comment]
Cool. Wish by boss had sent me to Evolve - seems great :)

Btw, what files/folders should be zipped? Zip the binaries, nupkgs separately?

**Comment by brianlagunas** [comment]
Just the binaries.  A lot of customers don't use NuGet and still rely on plain old assembly references.  So I was thinking of creating a folder structure similar to this under a parent Build folder where all our build scripts a stuff will go:

- Binaries
   - Core
   - WPF
   - Windows
   - Forms

We could add a post build process to the projects to copy the assemblies into those location.  Then our build process could zip the Binaries folder up as part of the build.

That's what was going through my head anyways.  Haven't really thought it out completely.

**Comment by brianlagunas** [comment]
I'm checking this out, but I don't see the new Test configuration.  T ru this, I am assuming I just need to run the build.ps1 script correct?

**Comment by brianlagunas** [comment]
I am in the process of research Appveyors ability to automatically do everything for me :)

**Pull request closed without merging**
