### PR TITLE
add PropertyChangedListener

### PR DESCRIPTION
**Pull request by runceel**
I create class that subscribe PropertyChanged event.
It's very useful.

It is the thing which was imitated this Japanese MVVM library.
http://ugaya40.hateblo.jp/entry/Livet

### CODE REVIEW

**Comment by brianlagunas** [comment]
What is the purpose of this class?  What problem does it solve?  How does it fit into Prism's current feature set?  I see this being a source a memory leaks.  Why are you not using weak references?

**Comment by runceel** [comment]
Thank you for your review.

> What is the purpose of this class? What problem does it solve? How does it fit into Prism's current feature set?

I always create Model wrapper class in ViewModel.
Like this.
https://github.com/runceel/Prism/blob/master/Source/Prism.Tests/Mocks/ViewModels/MockPropertyChangedViewModel.cs

This ViewModel class is little modify copy of Model. I subscribe PropertyChanged event and write ViewModel logic. This case, I think frequent in MVVM.I want a helper class.

>  I see this being a source a memory leaks. Why are you not using weak references?

I was changed to WeakReference.It's ok?
https://github.com/runceel/Prism/blob/master/Source/Prism/Mvvm/PropertyChangedListener.cs

**Comment by brianlagunas** [comment]
I'm not really seeing the benefit.  If the Model already implements INPC, then you can simply hook into the PropertyChanged event directly.

**Comment by runceel** [comment]
@brianlagunas . Thank you for review.

I do not want to write switch case statements, and WeakReference management.
But you tought that it's no benefit. I put into "my pocket library" to this class.

Thank you.

**Comment by brianlagunas** [comment]
I said I'm not seeing the benefit, not that there isn't one.  I am trying to understand exactly what this does.  Based on your description, it looks like it just lets you use a lambda to create a listener for a specific property name instead of using if/switch checks.  It is an interesting approach.

**Comment by runceel** [comment]
I can't speak English well. I'm sorry to be mislead.

I think that this is benefit.

### lambe event listener support
Normal case.
```cs
model.PropertyChanged += (s, e) =>
{
   // do something
};
```
This case's problem can't release subscribe.

PropertyChangedListener can release subscribe.

```cs
// field
private PropertyChangedListener Listener {get;}

// constructor
Listener = new PropertyChangedListener(model)
{
    "PropertyName", (s, e) => 
    {
        // do something
    }
};

// other method
Listener.Dispose(); // release subscribe
```

### no switch case/if statements
Normal case.
```cs
// constructor
model.PropertyChanged += Model_PropertyChanged;

// method
private void Model_PropertyChanged(object sender, Property...Args e)
{
    switch (e.PropertyName)
    {
        case "PropertyA":
            Foo();
            break;
         case "PropertyB":
             Bar();
             break;
         // etc...
    }
}
```

PropertyChangedListener can write declarative.
```cs
Listener = new PropertyChangedListener(model)
{
    { "PropertyA", (s, e) => Foo() },
    { "PropertyB", (s, e) => Bar() },
    // etc...
};
```

**Pull request closed without merging**
