### PR TITLE
change HardwareButtons to SystemNavigationManager

### PR DESCRIPTION
**Pull request by runceel**
Use new windows 10 uwp api. This way can work tablet mode ”back button”.

### CODE REVIEW

**Comment by briannoyes** [comment]
I think this goes against the design guidance I heard watching the Windows UWP MVA videos. There they said that for mobile apps if you are at the root of the navigation stack, the hardware back button should take you out to the OS level to be consistent with current Windows Phone behavior. But for any non-mobile app, you should do nothing when when you get to the root of the stack. 

I think we need to modify the code provided to have a separate handler for system back button nav to not Exit() unless it came from a hardware back button, which would only exist on a mobile platform device. Additionally, i think we need to add some management of the visibility of the system back button as outlined in this post:
http://www.wintellect.com/devcenter/jprosise/handling-the-back-button-in-windows-10-uwp-apps

Anyone disagree or have other suggestions?

**Comment by davidezordan** [comment]
@briannoyes I agree with that approach to keep consistency with the platform

**Comment by runceel** [comment]
Does best way remove Exit method?
I think that management of the visibility system back button, it write individual app.

**Comment by ElementalNex** [comment]
I added a new pull request #77 what u think of this implementation?

**Pull request closed without merging**
