### PR TITLE
Feature/xamarin forms 5 0 support

### PR DESCRIPTION
**Pull request by epsmae**
﻿## Description of Change

Upgraded Xamarin to version 5.0
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0

### Bugs Fixed

- https://github.com/PrismLibrary/Prism/issues/2239

### API Changes

None

### Behavioral Changes

None

### PR Checklist

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by epsmae** [comment]
The piplines have the following errors can I do something to avoid that?
```
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent
Error: Your billing plan does not allow you to run tests: Tests disabled
```

**Comment by dansiegel** [comment]
Thanks for the PR... I'll review this soon. Honestly it's the changes for the FlyoutPage that require the most intense review as I'm not sure without running this that the changes as is are quite appropriate.

**Comment by jBijsterboschNL** [comment]
What's the status of this PR? :) can't wait for this as we want to move to Xamarin.Forms 5.0. If I can assist with anything, please let me know.

**Comment by epsmae** [comment]
@dansiegel any update from your side?

**Comment by dansiegel** [comment]
@epsmae this PR changes some core implementations around the MasterDetailPage... There are some backchannel discussions that need to be resolved before we can move forward on this. Don't worry I haven't forgotten you

**Comment by yufhoyos** [comment]
Any news about this?

**Comment by brianlagunas** [comment]
@yufhoyos you'll know of any news when this PR is either merged or closed.

**Comment by dansiegel** [comment]
@epsmae my apologies for the delay in getting back to you on this PR. After further discussion with @brianlagunas we've decided that the solution here doesn't quite fit how we want to implement support for the FlyOutPage and we will be making the appropriate changes for the upcoming Prism 8.1.

**Comment by pasha-o** [comment]
hi, @dansiegel, @brianlagunas is there a timeline for the Prism 8.1 release? thanks for all of your great work.

**Comment by brianlagunas** [comment]
We are discussing the release schedule this week and should know something by next week.

**Comment by jBijsterboschNL** [comment]
@brianlagunas any updates on the timeline for the Prism 8.1 release, including Xamarin.Forms 5 compatibility?

**Comment by brianlagunas** [comment]
@jBijsterboschNL not yet. We are getting some last minute fixes in before release.

**Pull request closed without merging**
