### PR TITLE
Add async versions of INavigateAsync.RequestNavigate

### PR DESCRIPTION
**Pull request by frogger3d**
PR for #118

### CODE REVIEW

**Comment by brianlagunas** [comment]
This looks pretty good.  We want to get away from the extension methods and provide this functionality though the interfaces to make unit testing a little less painful for users.  We would also need to add this async call to the IRegionManager since it's possible to call RequestNavigate off of that class as well.  Can you modify this PR with those changes soon?  We are trying to get this in the Prism 6 release which we want to try to release this week.  Thanks

**Comment by frogger3d** [comment]
PR updated as requested.

I noticed there is a lack of unit tests on the navigation methods on RegionNavigationService. Not sure how to handle this.

**Comment by brianlagunas** [comment]
I think the tests are divided up between a number of fixtures like the NavigationAsyncExtensionsFixture.  The RequestNavigate methods used to be extension methods, and we have been moving them into the actual classes to eliminate the extension methods and improve testability.  We may have some gaps in those tests.

**Comment by brianlagunas** [comment]
Don't forget the IRegionManager :)

**Comment by frogger3d** [comment]
Please wait, I'm struggling with rebasing

**Comment by frogger3d** [comment]
Hm okay I guess the rebase went okay after all, it's ready.

I'm pretty sure this works, but I'd be happier if the internals of RegionNavigationService were build using async/await. I guess this should be postponed to a next PR as it is more invasive.

**Comment by brianlagunas** [comment]
Well, since we are trying to release Prism 6 this week.  Let's hold off on merging this until we can flush it out completely.  I would feel more comfortable if we took our time and made sure everything was working perfectly before adding it.  So, continue to work on this to get it just how you want it, then we will do a proper review of it.  Once merged, we can release it as an update.  What do you think?

**Comment by frogger3d** [comment]
This is the general idea.

Note that currently RegionNavigationServiceFixture.WhenNavigatingWithNullCallback_ThenThrows fails (and is commented out because it stalls all other tests) because the exception is not caught because the method is actually an async void that completes immediately.

**Comment by frogger3d** [comment]
Another possibly breaking change for some people is that the navigation events are now raised before the callback is called.

**Comment by brianlagunas** [comment]
We are going to close this until we can do a proper async navigation design review.

**Pull request closed without merging**
