### PR TITLE
Inject current page in pageDialogService

### LINKED ISSUE #254: [XF] PageDialogService is not setting Page property correctly
The PageDialogService is using the Page property, like the NavigationService does. However it uses the internal field to display alerts and action sheets which can cause NullReferenceExceptions. When using constructor injection the Page property does not get set.

The fix for this is to assign the Page property in the UnityBootstrapper class in the ConfigureViewModelLocator method.

This does however rely on the same solution as the NavigationService does, which means there is another fixed name constructor parameter (which in my opinion is a little bit fragile). I've seen another issue about this topic so I guess we shouldn't repeat that here.

Will add a PR soon.

### PR DESCRIPTION
**Pull request by Mardaneus86**
For the PageDialogService to work properly it needs to know the current page. This fix expands on the current solution for the NavigationService to the PageDialogService.

fixes #254

### CODE REVIEW

**Comment by brianlagunas** [comment]
Dang, I would really like to avoid this.  Have you tried just changing the service to use the property instead of the backing field?  For showing dialogs, it should be safe just to use the MainPage right?

**Comment by Mardaneus86** [comment]
I agree that it isn't the best solution. Just tested and changing the backing field to the property works. So it uses Application.Current.MainPage when the backing field is null. My only problem is that I don't understand why the PageDialogService needs the IPageAware interface, so I can't judge which is the better solution. Only thing I can think of is that it is needed is for unit testing purposes, is that correct?

Because the Page property from the IPageAware interface is defined as an explicit interface implementation, it can't be used directly without a compilation error. Changing it to a normal interface implementation can fix this issue, don't know if this causes any side effects.

I'd like to see your view on this, especially if my reasoning about why the IPageAware interface would be needed is correct?

Thanks for the feedback!

**Comment by brianlagunas** [comment]
Actually, that was only there for experimentation as part of the PR.  It was just never removed.  There is no need for that interface, and the Page property can just return the application mainpage.  Don't even need a backing field.

I am also going to look into other possible approaches to solve the parameter override issue, because the navigation service does rely on the page instance but I hate the naming limitation.

**Comment by Mardaneus86** [comment]
Okay, I'll remove the IPageAware interface from the PageDialogService implementation then and just use the application mainpage. Will push a new commit soon.

**Pull request merged**
