### PR TITLE
chore: Update to Uno 4.0 and WinAppSDK 1.0

### PR DESCRIPTION
**Pull request by jeromelaban**
﻿## Description of Change

Updates WinUI support to WinAppSDK 1.0 and Uno 4.0.

### Bugs Fixed

None.

### API Changes

None.

### Behavioral Changes

None.

### PR Checklist

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks @dansiegel !

**Comment by dansiegel** [comment]
Of course. Thanks for the update

**Comment by annmanvel** [comment]
Hi @brianlagunas , @dansiegel , @jeromelaban 

Is there anything which I can do to resolve this issue in my project which I shared in #2632?

**Comment by brianlagunas** [comment]
@annmanvel Fork the code, build it, and add the references directly to the assemblies or projects. Or wait for an official NuGet package to be released in the first part of 2022 due to day jobs and holidays.

**Comment by dansiegel** [comment]
Or you can become a Sponsor and access all of our CI builds from [Sponsor Connect](http://sponsorconnect.dev)

**Comment by annmanvel** [comment]
> 

Hi @brianlagunas , 
Any official NuGet package release planned for WinUI3 Prism for the issue #2632 ?

**Pull request merged**
