### PR TITLE
UWP Added LightInject

### PR DESCRIPTION
**Pull request by jorisdebock**
#238

### CODE REVIEW

**Comment by brianlagunas** [comment]
The samples in this repo are used for development efforts only, not as guidance.  There is no point in adding all the different container samples in this repo.  When the NuGets are available, these type of samples can be added to the Prism-Samples-Windows repo

**Comment by brianlagunas** [comment]
Please remove the samples from this PR, and we will review again.

**Comment by jorisdebock** [comment]
@brianlagunas why did @bartlannoeye then add a sample of my other pr?

**Comment by bartlannoeye** [comment]
@jorisdebock it was to validate that it actually "works", as we don't have any tests for UWP. But the team just discussed we shouldn't add a sample for each container and thus making future updates on the test app more complex. We should move to real unit tests, see #342. The other samples will be cleaned up one of these days as well, only leaving Unity in place.

Sorry for the effort put into creating a sample app.

**Comment by brianlagunas** [comment]
We never set any guidelines around this within the team until just right now :)

**Comment by jorisdebock** [comment]
ok :)

**Comment by brianlagunas** [comment]
We are not going to accept any new containers for UWP until we have had an opportunity to take a proper look at the current UWP codebase and re-evaluate our current approaches.

**Pull request closed without merging**
