### PR TITLE
add OnRestoreApplicationAsync

### PR DESCRIPTION
**Pull request by runceel**
I want method on restore custom process.

Because PrismApplication has OnSuspendingApplicationAsync method. I can suspend data, for example ApplicationData.Current.LocalFolder. But I can't restore that.

### CODE REVIEW

**Comment by runceel** [comment]
I mssed

**Comment by overrorflow** [comment]
@runceel your code similar this:

```cs
protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
{
    if(args.PreviousExecutionState == ApplicationExecutionState.Terminated)
    {
        ... // your behavior
    }
}
```

**Comment by runceel** [comment]
@overrorflow Thank you for your suggestion.
It's simple solution at PrismApplication. But I use PrismUnityApplication. PrismUnityApplication sealed this method.

**Comment by overrorflow** [comment]
@runceel and this is
```cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    base.OnLaunched(args);
    if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
    {
        ...
    }
}
```

**Comment by runceel** [comment]
base.OnLaunched method is async void. 

```cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    base.OnLaunched(args);
    if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
    {
        // after initialized frame? after navigated mainpag? after restored sessionstate? etc...
    }
}
```

I want a method that is called in between "initialized frame" and "navigate MainPage".

**Comment by briannoyes** [comment]
The normal way to handle this would be to write your custom state into the SessionStateService on suspend, then read it back out in your OnInitializeAsync override. Why won't that work here?

**Comment by runceel** [comment]
I use Prism.Unity.
PrismUnityApplication class sealed this method...

**Comment by briannoyes** [comment]
OK, I see what you mean now. sealed should never have been put on OnInitializeAsync. Will get that fixed and checked in shortly and we will push out an update to the nugets as soon as we can.

**Comment by runceel** [comment]
@briannoyes Thank you.

**Pull request closed without merging**
