### PR TITLE
Added SimpleInjector for UWP

### PR DESCRIPTION
**Pull request by jorisdebock**

### CODE REVIEW

**Comment by bartlannoeye** [comment]
Looks good on first sight, thanks for the effort!

**Comment by brianlagunas** [comment]
How about a nuspec file and an update to our nugget generator script too :)

**Comment by jorisdebock** [comment]
@brianlagunas here you go :) couldn't test it though

**Comment by brianlagunas** [comment]
Thanks.  I don't see the Release-Signed build configuration for this project.  Can you add it?  Just look at the other projects to compare.

**Comment by bartlannoeye** [comment]
No problem, I'll add it and test the signing and package right away.

**Comment by bartlannoeye** [comment]
You can get the pre-release package to test from https://www.myget.org/F/prismprerelease/api/v3/index.json while waiting for it to pop up on NuGet.

**Pull request merged**
