### PR TITLE
Added new navigation page provider

### PR DESCRIPTION
**Pull request by brianlagunas**
Added a new NaigationPageProviderAttribute and INavigationProvder interface to support configuring and wrapping pages during navigation.

### CODE REVIEW

**Comment by brianlagunas** [comment]
Please check out PR #195.

Create a new class that implement the INavigationPageProvider interface
```
    public class ViewANavigationPageProvider : INavigationPageProvider
    {
        Page _page = null;

        public void Initialize(Page page)
        {
            _page = page;
            NavigationPage.SetHasNavigationBar(_page, true);
            NavigationPage.SetBackButtonTitle(_page, "Go Back Sucka");
            NavigationPage.SetHasBackButton(_page, true);
        }

        public Page CreateNavigationPage()
        {
            var newPage = new NavigationPage(_page);
            newPage.BarBackgroundColor = Color.Green;
            newPage.BarTextColor = Color.White;
            return newPage;
        }
    }
```
Next attribute the Page that you are navigating to that you want to apply this provider to:
```
[NavigationPageProvider(typeof(ViewANavigationPageProvider))]
    public partial class ViewA : ContentPage
    {
        public ViewA()
        {
            InitializeComponent();
        }
    }
```
Now navigate:
```
_navigationService.Navigate("ViewA", parameters);
```

**Comment by brianlagunas** [comment]
This addresses #64 and #138

**Comment by brianlagunas** [comment]
I'm a little concerned with the naming I am using, as I fear it may cause confusion.  CreateNavigationPage doesn't mean you can only return a Xamarin.Forms.NavigationPage, it means you can crete any tyoe pf Page that you want to wrap/navigate to.

Maybe rename it to CreatePageForNavigation?

**Comment by brianlagunas** [comment]
I am also curious if I should reduce this interface down to a single method.  Get rid of the Initialize, and just provide the CreatePageForNavigation method?  Or should I keep both methods to keep clear what is expected?

**Comment by bartlannoeye** [comment]
Is there a reason to keep them separated? Can one be used without the other?

**Comment by brianlagunas** [comment]
yes, once can be used without the other.  The initialize can be used to configure various properties of the view.  Then return null on the CreatePageForNavigation so that the page isn't wrapped in a new page, like  Xamarin.Forms.NavigationPage for example.  I am not 100% sure how useful that is though.  If you are using this attribute, is the expectation that you will always be wrapping the page in a different parent for navigation?

**Pull request merged**
