### PR TITLE
Implementing Prism.Autofac.Forms

### PR DESCRIPTION
**Pull request by ederbond**
Hey @brianlagunas ,
I'm trying to implement Prism.Autofac.Forms but a little something is still missing.
My XF app is not navigating correctly could you help me ?

By the way, on Prism.Unity.Forms project I couldn't find out where did your Registered the Type UnityPageNavigationService witch you are resolving from the Unity container on Prism.Unity.PrismApplication.CreateNavigationService() --- (line 69 of PrismApplication class for Unity).

I think I'm really close to finish this implementantion but something is missing on my implementation that is preventing the app to Navigate correctly the MainPage of a clone of you sample for Unity.

### CODE REVIEW

**Comment by joacar** [comment]
Hi,

Good work. Some observations after a brief look

* You should provide a service key when registering the `PageDialogService` implementation.  (https://github.com/joacar/Prism/blob/7a204c22989b35a1acb2ffb9206f8946c5bbc5f2/Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs#74)
* Also you should provide a way to utilize `Xamarin.Forms.DependencyService` as fallback container.

Regarding the Page issue I will look closer at it when I have time

**Comment by brianlagunas** [comment]
I haven't looked at this closely, but one thing I did notice is that you aren't using the latest preview version of Xamarin.Forms which is what Prism is built against.  You need to update all your references.

**Comment by ederbond** [comment]
Ok @brianlagunas, I'll update Xamarin.Forms references and re-submit the poll request.
Two questions, 


I'm working on the "Master" branch, should I continue on this or make the changes on the "v6.2-Preview" ?

Is any of these two branches ("Master" and "v6.2-Preview") production ready ?
If not is there a time frame to release then for people use on production enviroment XF.apps ?

@joacar thanks for the feedback and tips. I'll look close to then and try to figure out the issues I'm facing.

**Comment by joacar** [comment]
What I usually do is creating a local branch from origin/master (i.e. the branch of this repository) and perform the work in that branch and later submit a PR. This way you avoid having all the files changed like this PR.

You should also add tests (see #535 for details).

I prefer if you create a new branch like above and implement your changes and then submit a new pr. @brianlagunas what do you think?

**Comment by brianlagunas** [comment]
I always create a branch and then submit my PRs from the branch. I never work on master directly.

**Comment by dansiegel** [comment]
@ederbond I would say that master is stable and should be safe to use in Production Apps. The prerelease status of the NuGet packages has to do with [bugs](https://github.com/PrismLibrary/Prism/milestones/Prism%20for%20Xamarin%20Forms%206.2) that Xamarin needs to fix first. 

Ultimately I would say the answer to your question, is the answer to, "Do you feel your app can be safely deployed with a prerelease of Xamarin Forms?" I think the answer to that, various for each of us based on both preferences, and project requirements.

**Comment by ederbond** [comment]
@dansiegel I agree that XF still have several bugs that needs to be addressed, but I think that many companies will avoid using Prism if it doesn't provide a nuget package that use the stable version of Xamarin.Forms
Many companies will argue that if prims will force them to use a version of Xamarin.Forms that is not marked as "Stable" by xamarin it could lead them to unkown but or things like that.

**Pull request closed without merging**
