### PR TITLE
Fix resume methods on app resume

### PR DESCRIPTION
**Pull request by nolanblew**
This fixes a bug in https://github.com/PrismLibrary/Prism/issues/795, allowing `OnNavigatedTo` to be called when the app is resuming from an in-memory resume (app has not been terminated yet).

### CODE REVIEW

**Comment by brianlagunas** [comment]
@bartlannoeye can you verify this?  Thanks

**Comment by bartlannoeye** [comment]
We're having a OnResumeApplicationAsync virtual method that should be plugged in so people can hook in their own logic as well. However we don't want this to trigger twice as the Activated event gets triggered as well when the resume is triggered by contract activation.

**Comment by nolanblew** [comment]
@bartlannoeye Which contracts are you referring to? I have created both Windows 10 contracts and the depreciated Windows 8 contracts (file pickers, camera UI, custom app contract) and none of them seem to activate `OnActivated` or `InitializeFrameAsync`, which call `OnResumeApplicationAsync`. The app doesn't appear to think that it's resuming at all. I have tested on a Windows 10 PC and a Windows 10 phone. Am I not understanding correctly what you mean by contract?

**Comment by bartlannoeye** [comment]
Quote from MSDN

> If a suspended app is activated to participate in an app contract or extension, it receives the Resuming event first, then the Activated event.

Must confess I didn't test last night as I was at a IoT presentation until 11 pm. Will be something for tonight. 

Either way, whether it's triggered or not, I think we still have to add the OnResumeApplicationAsync call to allow people to inject their own logic.

**Pull request merged**
