### PR TITLE
Ability to select tabs from TabbedPage's TitleView

### PR DESCRIPTION
**Pull request by mhrastegari**
﻿## Description of Change
In some of our projects we needed to navigate to tabs from the main `TitleView` so we changed a little bit of the `TabbedPage` code. 
Hope it'll be useful for you guys and users too. ❤️

### CODE REVIEW

**Comment by dansiegel** [comment]
Thanks for the PR. Looks good to me. Are you able to add a test for the scenario? We won't be able to merge until we get the build pipelines fixed but this should be fine to get in before we do the next release.

**Comment by mhrastegari** [comment]
You mean I tell how to test it? 
or writing unit tests? because I'm kinda still not familiar with tests. 🥲

**Comment by dansiegel** [comment]
@mhrastegari thanks for the PR I've rebased this on the latest changes and added some unit tests. I would encourage you to take a look so that next time you'll have a better understanding to be able to contribute some tests along the way :)

**Comment by mhrastegari** [comment]
Sure Dan :) thank you ❤️

**Pull request merged**
